import { Router, type Response } from 'express';
import { authService } from '../services/auth.service';
import type { AuthenticatedRequest } from '../middleware/auth';

export const authRouter = Router();

/**
 * POST /api/v1/auth/signup
 * Register a new user and create an isolated workspace
 */
authRouter.post('/signup', async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  try {
    const { email, password, fullName, companyName, defaultCurrency } = req.body;

    if (!email || !password || !fullName) {
      res.status(400).json({
        error: 'Validation failed',
        message: 'email, password, and fullName are mandatory fields.'
      });
      return;
    }

    if (password.length < 8) {
      res.status(400).json({
        error: 'Validation failed',
        message: 'Password must be at least 8 characters long.'
      });
      return;
    }

    const authData = await authService.signup({
      email,
      password,
      fullName,
      companyName,
      defaultCurrency
    });

    res.status(201).json({
      success: true,
      message: 'Account created successfully with private workspace.',
      data: authData
    });
  } catch (error: any) {
    res.status(400).json({
      error: 'Registration failed',
      message: error.message || 'Unable to complete signup.'
    });
  }
});

/**
 * POST /api/v1/auth/login
 * Authenticate user credentials and return JWT session token
 */
authRouter.post('/login', async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      res.status(400).json({
        error: 'Validation failed',
        message: 'email and password are required.'
      });
      return;
    }

    const authData = await authService.login({ email, password });

    res.status(200).json({
      success: true,
      message: 'Login successful.',
      data: authData
    });
  } catch (error: any) {
    res.status(401).json({
      error: 'Authentication failed',
      message: error.message || 'Invalid credentials.'
    });
  }
});

/**
 * GET /api/v1/auth/me
 * Get current authenticated user session and workspace profile
 */
authRouter.get('/me', async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  try {
    if (!req.user || !req.user.id) {
      res.status(401).json({
        error: 'Unauthorized',
        message: 'No active authenticated session.'
      });
      return;
    }

    const profile = await authService.getProfile(req.user.id);

    res.status(200).json({
      success: true,
      data: profile || req.user
    });
  } catch (error: any) {
    res.status(500).json({
      error: 'Internal Server Error',
      message: error.message || 'Could not fetch profile.'
    });
  }
});

/**
 * POST /api/v1/auth/logout
 */
authRouter.post('/logout', async (_req: AuthenticatedRequest, res: Response): Promise<void> => {
  res.status(200).json({
    success: true,
    message: 'Logged out successfully.'
  });
});

/**
 * PATCH /api/v1/auth/profile
 * Update user settings (full name, company name, default currency)
 */
authRouter.patch('/profile', async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  try {
    if (!req.user?.id) {
      res.status(401).json({ error: 'Unauthorized' });
      return;
    }
    const updated = await authService.updateProfile(req.user.id, req.body || {});
    res.status(200).json({
      success: true,
      message: 'Profile updated successfully.',
      data: updated
    });
  } catch (error: any) {
    res.status(400).json({
      error: 'Update failed',
      message: error.message || 'Could not update profile.'
    });
  }
});

/**
 * GET /api/v1/auth/api-keys
 * Retrieve API keys generated by the authenticated user
 */
authRouter.get('/api-keys', (req: AuthenticatedRequest, res: Response): void => {
  if (!req.user?.id) {
    res.status(401).json({ error: 'Unauthorized' });
    return;
  }
  const keys = authService.listApiKeys(req.user.id);
  res.status(200).json({
    success: true,
    data: keys.map(k => ({
      id: k.id,
      name: k.name,
      keyPrefix: k.keyPrefix,
      createdAt: k.createdAt,
      lastUsed: k.lastUsed
    }))
  });
});

/**
 * POST /api/v1/auth/api-keys
 * Generate a new programmatic API key for the user
 */
authRouter.post('/api-keys', (req: AuthenticatedRequest, res: Response): void => {
  if (!req.user?.id) {
    res.status(401).json({ error: 'Unauthorized' });
    return;
  }
  const name = req.body?.name || 'Custom Integration Key';
  const newKey = authService.createApiKey(req.user.id, name);
  res.status(201).json({
    success: true,
    message: 'API Key generated successfully.',
    data: newKey
  });
});

/**
 * DELETE /api/v1/auth/api-keys/:id
 * Revoke an API key
 */
authRouter.delete('/api-keys/:id', (req: AuthenticatedRequest, res: Response): void => {
  if (!req.user?.id) {
    res.status(401).json({ error: 'Unauthorized' });
    return;
  }
  const id = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const deleted = authService.deleteApiKey(req.user.id, id);
  if (!deleted) {
    res.status(404).json({ error: 'Key not found' });
    return;
  }
  res.status(200).json({
    success: true,
    message: 'API Key revoked successfully.'
  });
});

/**
 * GET /api/v1/auth/activity
 * Retrieve persistent activity and data audit logs for this specific user
 */
authRouter.get('/activity', (req: AuthenticatedRequest, res: Response): void => {
  if (!req.user?.id) {
    res.status(401).json({ error: 'Unauthorized' });
    return;
  }
  const limit = req.query.limit ? Number(req.query.limit) : 50;
  const logs = authService.getActivityLogs(req.user.id, limit);
  res.status(200).json({
    success: true,
    data: logs
  });
});

